=== alexandruionascu/uvt/xml/hw2/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="articles">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="article">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="faculty" type="xs:string" />
                    <xs:element name="title" type="xs:string" />
                    <xs:element name="publish_date" type="xs:date" />
                    <xs:element name="isbn" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="authorId" type="xs:string" use="optional" />
                  <xs:attribute name="categoryId" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="authors">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="author">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="affiliations">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="affiliation" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="categories">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="category">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="type" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alexandruionascu/uvt/xml/hw5/spring-camel-rest-dsl-master/data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<catalog
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <articles>
        <article id="bk101" authorId="au01" categoryId="ctg02">
            <faculty>Computer Science</faculty>
            <id>1</id>
            <title>XML Developer's Guide</title>
            <publish_date>2000-10-01</publish_date>
            <isbn>978-3-16-148410-0</isbn>
        </article>
        <article id="bk102" categoryId="ctg01">
            <id>2</id>
            <faculty>Computer Science</faculty>
            <title>Json Developer's Guide</title>
            <publish_date>2000-01-01</publish_date>
            <isbn>861-2-22-141480-2</isbn>
        </article>
    </articles>
    <authors>
        <author id="au01">
            <name>Gambardella, Matthew</name>
            <affiliations>
                <affiliation>
                    <name>West University of Timisoara</name>
                </affiliation>
                <affiliation>
                    <name>University of Berlin</name>
                </affiliation>
            </affiliations>
        </author>
        <author id="au02">
            <name>Simone, Nelson</name>
            <affiliations>
                <affiliation>
                    <name>University of Prague</name>
                </affiliation>
            </affiliations>
        </author>
    </authors>
    <categories>
        <category id="ctg01" type="journal">
            <name>IEEE Transactions on Evolutionary Computation</name>
        </category>
        <category id="ctg02" type="conference">
            <name>ACM Conference of London</name>
        </category>
    </categories>
</catalog>
